(() => {
var exports = {};
exports.id = 888;
exports.ids = [888];
exports.modules = {

/***/ 953:
/***/ ((module) => {

// Exports
module.exports = {
	"Sidenav": "Sidenav_Sidenav__o2hgf"
};


/***/ }),

/***/ 403:
/***/ ((module) => {

// Exports
module.exports = {
	"FMNavLink": "FMNavLink_FMNavLink__NsFKX",
	"active-link": "FMNavLink_active-link__2Nghu"
};


/***/ }),

/***/ 162:
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  "default": () => (/* binding */ _app)
});

// EXTERNAL MODULE: external "react/jsx-runtime"
var jsx_runtime_ = __webpack_require__(997);
;// CONCATENATED MODULE: external "next/head"
const head_namespaceObject = require("next/head");
var head_default = /*#__PURE__*/__webpack_require__.n(head_namespaceObject);
// EXTERNAL MODULE: external "react"
var external_react_ = __webpack_require__(689);
// EXTERNAL MODULE: ./node_modules/next/link.js
var next_link = __webpack_require__(664);
;// CONCATENATED MODULE: external "next/router"
const router_namespaceObject = require("next/router");
// EXTERNAL MODULE: ./src/components/core/FMNavLink.module.scss
var FMNavLink_module = __webpack_require__(403);
var FMNavLink_module_default = /*#__PURE__*/__webpack_require__.n(FMNavLink_module);
;// CONCATENATED MODULE: ./src/components/core/FMNavLink.tsx





const FMNavLink = ({ label , url  })=>{
    const router = (0,router_namespaceObject.useRouter)();
    const classes = [
        (FMNavLink_module_default()).FMNavLink,
        router.pathname == url ? (FMNavLink_module_default())["active-link"] : '', 
    ];
    return(/*#__PURE__*/ jsx_runtime_.jsx(next_link["default"], {
        href: url,
        children: /*#__PURE__*/ jsx_runtime_.jsx("a", {
            className: classes.join(' '),
            children: label
        })
    }));
};

;// CONCATENATED MODULE: ./src/components/core/index.ts


// EXTERNAL MODULE: ./src/components/Sidenav/Sidenav.module.scss
var Sidenav_module = __webpack_require__(953);
var Sidenav_module_default = /*#__PURE__*/__webpack_require__.n(Sidenav_module);
;// CONCATENATED MODULE: ./src/components/Sidenav/Sidenav.tsx




const LINKS = [
    {
        url: '/',
        label: 'home'
    },
    {
        url: '/developer',
        label: 'developer'
    },
    {
        url: '/writer',
        label: 'writer'
    },
    {
        url: '/drummer',
        label: 'drummer'
    }, 
];
function Sidenav() {
    return(/*#__PURE__*/ jsx_runtime_.jsx("nav", {
        className: (Sidenav_module_default()).Sidenav,
        children: /*#__PURE__*/ jsx_runtime_.jsx("ul", {
            children: LINKS.map((link)=>/*#__PURE__*/ jsx_runtime_.jsx("li", {
                    children: /*#__PURE__*/ jsx_runtime_.jsx(FMNavLink, {
                        ...link
                    })
                }, link.url)
            )
        })
    }));
}

;// CONCATENATED MODULE: ./src/components/index.ts


;// CONCATENATED MODULE: ./pages/_app.tsx






function MyApp({ Component , pageProps  }) {
    return(/*#__PURE__*/ (0,jsx_runtime_.jsxs)("div", {
        className: "App",
        children: [
            /*#__PURE__*/ (0,jsx_runtime_.jsxs)((head_default()), {
                children: [
                    /*#__PURE__*/ jsx_runtime_.jsx("title", {
                        children: "Create Next App"
                    }),
                    /*#__PURE__*/ jsx_runtime_.jsx("meta", {
                        name: "description",
                        content: "Generated by create next app"
                    }),
                    /*#__PURE__*/ jsx_runtime_.jsx("link", {
                        rel: "icon",
                        href: "/favicon.ico"
                    })
                ]
            }),
            /*#__PURE__*/ jsx_runtime_.jsx("header", {
                children: /*#__PURE__*/ jsx_runtime_.jsx(next_link["default"], {
                    href: "/",
                    children: /*#__PURE__*/ jsx_runtime_.jsx("a", {
                        children: /*#__PURE__*/ jsx_runtime_.jsx("h1", {
                            children: "Fabricio Julian C. Montenegro"
                        })
                    })
                })
            }),
            /*#__PURE__*/ (0,jsx_runtime_.jsxs)("div", {
                className: "content",
                children: [
                    /*#__PURE__*/ jsx_runtime_.jsx("aside", {
                        children: /*#__PURE__*/ jsx_runtime_.jsx(Sidenav, {})
                    }),
                    /*#__PURE__*/ jsx_runtime_.jsx("main", {
                        children: /*#__PURE__*/ jsx_runtime_.jsx(Component, {
                            ...pageProps
                        })
                    })
                ]
            }),
            /*#__PURE__*/ jsx_runtime_.jsx("footer", {
                children: "Copyright \xa9 2021 Fabricio Julian C. Montenegro"
            })
        ]
    }));
}
/* harmony default export */ const _app = (MyApp);


/***/ }),

/***/ 562:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/server/denormalize-page-path.js");

/***/ }),

/***/ 14:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/i18n/normalize-locale-path.js");

/***/ }),

/***/ 524:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/is-plain-object.js");

/***/ }),

/***/ 20:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/mitt.js");

/***/ }),

/***/ 964:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/router-context.js");

/***/ }),

/***/ 565:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/router/utils/get-asset-path-from-route.js");

/***/ }),

/***/ 365:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/router/utils/get-middleware-regex.js");

/***/ }),

/***/ 428:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/router/utils/is-dynamic.js");

/***/ }),

/***/ 292:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/router/utils/parse-relative-url.js");

/***/ }),

/***/ 979:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/router/utils/querystring.js");

/***/ }),

/***/ 52:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/router/utils/resolve-rewrites.js");

/***/ }),

/***/ 226:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/router/utils/route-matcher.js");

/***/ }),

/***/ 422:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/router/utils/route-regex.js");

/***/ }),

/***/ 232:
/***/ ((module) => {

"use strict";
module.exports = require("next/dist/shared/lib/utils.js");

/***/ }),

/***/ 689:
/***/ ((module) => {

"use strict";
module.exports = require("react");

/***/ }),

/***/ 997:
/***/ ((module) => {

"use strict";
module.exports = require("react/jsx-runtime");

/***/ })

};
;

// load runtime
var __webpack_require__ = require("../webpack-runtime.js");
__webpack_require__.C(exports);
var __webpack_exec__ = (moduleId) => (__webpack_require__(__webpack_require__.s = moduleId))
var __webpack_exports__ = __webpack_require__.X(0, [730,664], () => (__webpack_exec__(162)));
module.exports = __webpack_exports__;

})();