import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import '../styles/App.scss';
import { Sidenav } from '../src/components';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className="App">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <a href="/">
          <h1>Fabricio Julian C. Montenegro</h1>
        </a>
      </header>
      <div className="content">
        <aside>
          <Sidenav />
        </aside>
        <main>
          <Component {...pageProps} />
        </main>
      </div>
      <footer>Copyright &copy; 2021 Fabricio Julian C. Montenegro</footer>
    </div>
  );
}

export default MyApp;
